[tool.poetry]
name = "coding-practice-leetcode"
version = "0.1.0"
description = "Coding practice in LeetCode"
authors = ["dongminlee94 <kid33629@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "22.3.0"
isort = "5.10.1"
pre-commit = "2.14.0"

[build-system]
requires = [
    "build>=0.7",
    "setuptools>=59.4",
    "wheel>=0.37",
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 104
target-version = ["py38"]
exclude = ""

[tool.isort]
profile = "black"
skip_gitignore = true
extend_skip_glob = ""
