name: "Repo CI] Python Code"

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Initial setup
      shell: bash -l {0}
      run: make init
    - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
